In [1]:
%matplotlib inline
import matplotlib as lib
import pandas as pd
from bs4 import BeautifulSoup
import requests

# Top Grossing Movies: 
1. Get the data
2. Clean and data
3. Transform to Pandas framework
4. Do calculation if neccessary
5. Explore!

In [72]:
#Get the data and clean the data
t=requests.get("http://www.the-numbers.com/movie/records/All-Time-Domestic-Box-Office")
soup=BeautifulSoup(t.text)
soup.prettify()
tgm=soup.find_all("tr")
topGrossingMovies={'Movie Name':[],"Year":[],"Domestic Box Office":[], "International Box Office":[],"Worldwide Box Office": []}
for i in range(1, len(tgm)):
    x= tgm[i].find_all("td")
    topGrossingMovies['Year'].append(int(x[1].get_text().strip()))
    topGrossingMovies['Movie Name'].append(x[2].get_text().strip())    
    topGrossingMovies['Domestic Box Office'].append(int(x[3].get_text().replace('$','').replace(',','').strip()))
    topGrossingMovies['International Box Office'].append(int(x[4].get_text().replace('$','').replace(',','').strip()))
    topGrossingMovies['Worldwide Box Office'].append(int(x[5].get_text().replace('$','').replace(',','').strip()))
topGrossingMovies

/usr/local/lib/python3.5/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))

{'Domestic Box Office': [936662225,
  760507625,
  658672302,
  652198010,
  623279547,
  533345358,
  483572795,
  474544677,
  460998007,
  459005868,
  448139099,
  441226247,
  435110554,
  424668047,
  423315812,
  422780140,
  415004880,
  408992272,
  408061789,
  408010692,
  403706375,
  402111870,
  400738009,
  395708305,
  381011219,
  380529370,
  380270577,
  377845905,
  373524485,
  370782930,
  368065385,
  363936910,
  363070709,
  361921605,
  356461711,
  352390543,
  351032910,
  350126372,
  342548984,
  341268248,
  337135885,
  336530303,
  336045770,
  334191110,
  333172112,
  330360194,
  330151138,
  322719944,
  319246193,
  318604126,
  317575550,
  317023851,
  315544750,
  312433331,
  310676740,
  309420425,
  309205079,
  307859516,
  306169255,
  305411224,
  304360277,
  303003568,
  301959197,
  300531751,
  296623634,
  295983305,
  293506292,
  293004164,
  292576195,
  292324737,
  292004738,
  291710957,
  291045518,
  290271960,
  290013036,
  289423425,
  285761243,
  281723902,
  281553689,
  281287133,
  279167575,
  277322503,
  274092705,
  268488329,
  267655011,
  262030663,
  261987880,
  261441092,
  260044825,
  260000000,
  259746958,
  258366855,
  257784718,
  257730019,
  256393010,
  255959475,
  255119788,
  254464305,
  251513985,
  251188924],
 'International Box Office': [1122000000,
  2023411357,
  1548943366,
  1018130015,
  896200000,
  469546000,
  467000000,
  552500000,
  325600000,
  945700000,
  636300000,
  495781885,
  357854772,
  440200000,
  642900000,
  564700000,
  654813349,
  806400000,
  743600000,
  269912687,
  418000000,
  434407829,
  873496971,
  643104279,
  960500000,
  555900000,
  468728300,
  763562762,
  410180516,
  251637737,
  606808379,
  599900000,
  420700000,
  429441164,
  497461374,
  771400000,
  1162986161,
  197200000,
  592154195,
  680500000,
  429516403,
  554345000,
  827578711,
  691300000,
  438000000,
  537800000,
  349706026,
  484610992,
  389026399,
  263839000,
  657179821,
  469534294,
  571672938,
  311128000,
  346018875,
  654000000,
  263500000,
  392000000,
  511231623,
  329542879,
  806166704,
  714000000,
  633124489,
  405571077,
  390934093,
  664300000,
  379300000,
  438538457,
  540008221,
  537400000,
  650939197,
  428828615,
  376954000,
  243900000,
  606898042,
  270334294,
  190923432,
  368799525,
  457023240,
  408132918,
  237400000,
  188441583,
  442300000,
  475100000,
  224157783,
  495859604,
  616991754,
  353285660,
  85096578,
  210700000,
  454654931,
  702000000,
  199944670,
  127950427,
  329139674,
  49746319,
  700000000,
  332000000,
  291981048,
  160160000],
 'Movie Name': ['Star Wars Ep. VII: The Force Awakens',
  'Avatar',
  'Titanic',
  'Jurassic World',
  'The Avengers',
  'The Dark Knight',
  'Finding Dory',
  'Star Wars Ep. I: The Phantom Menace',
  'Star Wars Ep. IV: A New Hope',
  'Avengers: Age of Ultron',
  'The Dark Knight Rises',
  'Shrek 2',
  'ET: The Extra-Terrestrial',
  'The Hunger Games: Catching Fire',
  "Pirates of the Caribbean: Dead Man's Chest",
  'The Lion King',
  'Toy Story 3',
  'Iron Man 3',
  'Captain America: Civil War',
  'The Hunger Games',
  'Spider-Man',
  'Transformers: Revenge of the Fallen',
  'Frozen',
  'Jurassic Park',
  'Harry Potter and the Deathly Hallows: Part II',
  'Finding Nemo',
  'Star Wars Ep. III: Revenge of the Sith',
  'The Lord of the Rings: The Return of the King',
  'Spider-Man 2',
  'The Passion of the Christ',
  'Despicable Me 2',
  'The Jungle Book',
  'Deadpool',
  'The Secret Life of Pets',
  'Inside Out',
  'Transformers: Dark of the Moon',
  'Furious 7',
  'American Sniper',
  'The Lord of the Rings: The Two Towers',
  'Zootopia',
  'The Hunger Games: Mockingjay - Part 1',
  'Spider-Man 3',
  'Minions',
  'Alice in Wonderland',
  'Guardians of the Galaxy',
  'Batman v Superman: Dawn of Justice',
  'Forrest Gump',
  'Shrek the Third',
  'Transformers',
  'Iron Man',
  'Harry Potter and the Sorcerer√¢\x80\x99s Stone',
  'Indiana Jones and the Kingdom of the Crystal Skull',
  'The Lord of the Rings: The Fellowship of the Ring',
  'Iron Man 2',
  'Star Wars Ep. II: Attack of the Clones',
  "Pirates of the Caribbean: At World's End",
  'Star Wars Ep. VI: Return of the Jedi',
  'Suicide Squad',
  'Independence Day',
  'Pirates of the Caribbean: The Curse of the Black Pearl',
  'Skyfall',
  'The Hobbit: An Unexpected Journey',
  'Harry Potter and the Half-Blood Prince',
  'The Twilight Saga: Eclipse',
  'The Twilight Saga: New Moon',
  'Harry Potter and the Deathly Hallows: Part I',
  'The Sixth Sense',
  'Up',
  'Inception',
  'The Twilight Saga: Breaking Dawn, Part 2',
  'Harry Potter and the Order of the Phoenix',
  'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
  'Man of Steel',
  'Star Wars Ep. V: The Empire Strikes Back',
  'Harry Potter and the Goblet of Fire',
  'Monsters, Inc.',
  'Home Alone',
  'The Hunger Games: Mockingjay - Part 2',
  'The Matrix Reloaded',
  'The Twilight Saga: Breaking Dawn, Part 1',
  'Meet the Fockers',
  'The Hangover',
  'Gravity',
  'Monsters University',
  'Shrek',
  'The Amazing Spider-Man',
  'Harry Potter and the Chamber of Secrets',
  'The Incredibles',
  'How the Grinch Stole Christmas',
  'Jaws',
  'Captain America: The Winter Soldier',
  'The Hobbit: The Desolation of Smaug',
  'The Lego Movie',
  'Star Trek',
  'I am Legend',
  'The Blind Side',
  'The Hobbit: The Battle of the Five Armies',
  'The Hangover Part II',
  'Despicable Me',
  'Batman'],
 'Worldwide Box Office': [2058662225,
  2783918982,
  2207615668,
  1670328025,
  1519479547,
  1002891358,
  950572795,
  1027044677,
  786598007,
  1404705868,
  1084439099,
  937008132,
  792965326,
  864868047,
  1066215812,
  987480140,
  1069818229,
  1215392272,
  1151661789,
  677923379,
  821706375,
  836519699,
  1274234980,
  1038812584,
  1341511219,
  936429370,
  848998877,
  1141408667,
  783705001,
  622420667,
  974873764,
  963836910,
  783770709,
  791362769,
  853923085,
  1123790543,
  1514019071,
  547326372,
  934703179,
  1021768248,
  766652288,
  890875303,
  1163624481,
  1025491110,
  771172112,
  868160194,
  679857164,
  807330936,
  708272592,
  582443126,
  974755371,
  786558145,
  887217688,
  623561331,
  656695615,
  963420425,
  572705079,
  699859516,
  817400878,
  634954103,
  1110526981,
  1017003568,
  935083686,
  706102828,
  687557727,
  960283305,
  672806292,
  731542621,
  832584416,
  829724737,
  942943935,
  720539572,
  667999518,
  534171960,
  896911078,
  559757719,
  476684675,
  650523427,
  738576929,
  689420051,
  516567575,
  465764086,
  716392705,
  743588329,
  491812794,
  757890267,
  878979634,
  614726752,
  345141403,
  470700000,
  714401889,
  960366855,
  457729388,
  385680446,
  585532684,
  305705794,
  955119788,
  586464305,
  543495033,
  411348924],
 'Year': [2015,
  2009,
  1997,
  2015,
  2012,
  2008,
  2016,
  1999,
  1977,
  2015,
  2012,
  2004,
  1982,
  2013,
  2006,
  1994,
  2010,
  2013,
  2016,
  2012,
  2002,
  2009,
  2013,
  1993,
  2011,
  2003,
  2005,
  2003,
  2004,
  2004,
  2013,
  2016,
  2016,
  2016,
  2015,
  2011,
  2015,
  2014,
  2002,
  2016,
  2014,
  2007,
  2015,
  2010,
  2014,
  2016,
  1994,
  2007,
  2007,
  2008,
  2001,
  2008,
  2001,
  2010,
  2002,
  2007,
  1983,
  2016,
  1996,
  2003,
  2012,
  2012,
  2009,
  2010,
  2009,
  2010,
  1999,
  2009,
  2010,
  2012,
  2007,
  2005,
  2013,
  1980,
  2005,
  2001,
  1990,
  2015,
  2003,
  2011,
  2004,
  2009,
  2013,
  2013,
  2001,
  2012,
  2002,
  2004,
  2000,
  1975,
  2014,
  2013,
  2014,
  2009,
  2007,
  2009,
  2014,
  2011,
  2010,
  1989]}

In [77]:
# Put the data into framework
bdf=pd.DataFrame(topGrossingMovies)
bdf=bdf[['Movie Name','Year','Domestic Box Office','International Box Office','Worldwide Box Office']]
bdf.index=bdf.index +1
bdf

,Movie Name,Year,Domestic Box Office,International Box Office,Worldwide Box Office
1,Star Wars Ep. VII: The Force Awakens,2015,936662225,1122000000,2058662225
2,Avatar,2009,760507625,2023411357,2783918982
3,Titanic,1997,658672302,1548943366,2207615668
4,Jurassic World,2015,652198010,1018130015,1670328025
5,The Avengers,2012,623279547,896200000,1519479547
6,The Dark Knight,2008,533345358,469546000,1002891358
7,Finding Dory,2016,483572795,467000000,950572795
8,Star Wars Ep. I: The Phantom Menace,1999,474544677,552500000,1027044677
9,Star Wars Ep. IV: A New Hope,1977,460998007,325600000,786598007
10,Avengers: Age of Ultron,2015,459005868,945700000,1404705868
11,The Dark Knight Rises,2012,448139099,636300000,1084439099
12,Shrek 2,2004,441226247,495781885,937008132
13,ET: The Extra-Terrestrial,1982,435110554,357854772,792965326
14,The Hunger Games: Catching Fire,2013,424668047,440200000,864868047
15,Pirates of the Caribbean: Dead Man's Chest,2006,423315812,642900000,1066215812
16,The Lion King,1994,422780140,564700000,987480140
17,Toy Story 3,2010,415004880,654813349,1069818229
18,Iron Man 3,2013,408992272,806400000,1215392272
19,Captain America: Civil War,2016,408061789,743600000,1151661789
20,The Hunger Games,2012,408010692,269912687,677923379
21,Spider-Man,2002,403706375,418000000,821706375
22,Transformers: Revenge of the Fallen,2009,402111870,434407829,836519699
23,Frozen,2013,400738009,873496971,1274234980
24,Jurassic Park,1993,395708305,643104279,1038812584
25,Harry Potter and the Deathly Hallows: Part II,2011,381011219,960500000,1341511219
26,Finding Nemo,2003,380529370,555900000,936429370
27,Star Wars Ep. III: Revenge of the Sith,2005,380270577,468728300,848998877
28,The Lord of the Rings: The Return of the King,2003,377845905,763562762,1141408667
29,Spider-Man 2,2004,373524485,410180516,783705001
30,The Passion of the Christ,2004,370782930,251637737,622420667
...,...,...,...,...,...
71,Harry Potter and the Order of the Phoenix,2007,292004738,650939197,942943935
72,"The Chronicles of Narnia: The Lion, the Witch ...",2005,291710957,428828615,720539572
73,Man of Steel,2013,291045518,376954000,667999518
74,Star Wars Ep. V: The Empire Strikes Back,1980,290271960,243900000,534171960
75,Harry Potter and the Goblet of Fire,2005,290013036,606898042,896911078
76,"Monsters, Inc.",2001,289423425,270334294,559757719
77,Home Alone,1990,285761243,190923432,476684675
78,The Hunger Games: Mockingjay - Part 2,2015,281723902,368799525,650523427
79,The Matrix Reloaded,2003,281553689,457023240,738576929
80,"The Twilight Saga: Breaking Dawn, Part 1",2011,281287133,408132918,689420051
81,Meet the Fockers,2004,279167575,237400000,516567575
82,The Hangover,2009,277322503,188441583,465764086
83,Gravity,2013,274092705,442300000,716392705
84,Monsters University,2013,268488329,475100000,743588329
85,Shrek,2001,267655011,224157783,491812794
86,The Amazing Spider-Man,2012,262030663,495859604,757890267
87,Harry Potter and the Chamber of Secrets,2002,261987880,616991754,878979634
88,The Incredibles,2004,261441092,353285660,614726752
89,How the Grinch Stole Christmas,2000,260044825,85096578,345141403
90,Jaws,1975,260000000,210700000,470700000
91,Captain America: The Winter Soldier,2014,259746958,454654931,714401889
92,The Hobbit: The Desolation of Smaug,2013,258366855,702000000,960366855
93,The Lego Movie,2014,257784718,199944670,457729388
94,Star Trek,2009,257730019,127950427,385680446
95,I am Legend,2007,256393010,329139674,585532684
96,The Blind Side,2009,255959475,49746319,305705794
97,The Hobbit: The Battle of the Five Armies,2014,255119788,700000000,955119788
98,The Hangover Part II,2011,254464305,332000000,586464305
99,Despicable Me,2010,251513985,291981048,543495033
100,Batman,1989,251188924,160160000,411348924

In [78]:
bdf.to_csv("TopGrossingMovies.csv")

In [67]:
#get CPI data
cpidata = pd.read_excel("cpi_data.xlsx", skiprows=range(9), header=1)
cols=list(cpidata)
cols.remove('Year')
cols.remove('HALF1')
cols.remove('HALF2')
cpidata["Average"]=cpidata[cols].mean(axis=1)
cpia=cpidata[['Year','Average']]
# cpia=cpia.set_index(keys="Year")
cpia.tail()

    Year     Average
48  2012  229.593917
49  2013  232.957083
50  2014  236.736167
51  2015  237.017000
52  2016  238.782333